[package]
name = "interview"
version = "0.1.0"
authors = ["huang.xiangdong <996514515@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
